---
debug: true
authPort: 50051
userPort: 50052
metricsPort1: 8081
metricsPort2: 8082
db:
  username: token
  path: ./secure-connect-chat.zip
  timeout: 30
  # Todo check if they must be here
  # for local testing
  localHost: 127.0.0.1
  localDBPort: 9092