name: Lint workflow [Golangci-lint]

on:
  workflow_call:

permissions:
  contents: read
  id-token: write      

env:
  GO_VERSION: '1.25.0'              
  GOLANGCI_LINT_VERSION: 'v2.4.0' 

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      # ✅ safer module detection with fallback if mono-repo without multiple modules
      - name: Detect Go modules
        id: set-modules
        shell: bash
        run: |
          MODULE_DIRS=$(go list -m -json 2>/dev/null | jq -s '[.[].Dir]')
          if [[ -z "$MODULE_DIRS" || "$MODULE_DIRS" == "[]" ]]; then
            MODULE_DIRS='["."]'
          fi
          echo "modules=${MODULE_DIRS}" >> "$GITHUB_OUTPUT"

  golangci-lint:
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
      fail-fast: false
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      # ✅ Cache Go build cache too, improves lint performance
      - name: Cache Go Build & Module Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-cache-${{ runner.os }}-${{ env.GO_VERSION }}-

      # ✅ Cache lint binary itself, pinned version helps cache hits
      - name: Cache golangci-lint binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: golangci-lint-${{ runner.os }}-${{ env.GOLANGCI_LINT_VERSION }}
          restore-keys: |
            golangci-lint-${{ runner.os }}-

      - name: Run golangci-lint (${{ matrix.module }})
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.module }}
          args: --timeout=5m  # ✅ avoids stuck jobs in CI
