name: Pull request

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  unit-test:
    uses: ./.github/workflows/unit-test.yml
  publish-test-results:
    needs:
      - unit-test
    runs-on: ubuntu-latest
    permissions:
      checks: write
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          # Docker build artifacts have to ignored
          # https://github.com/actions/toolkit/pull/1874
          pattern: "!*.dockerbuild"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          comment_mode: off
